site_name: UIkit 日本語ドキュメント
site_description: UIkit の日本語意訳・再構成ドキュメント
docs_dir: docs
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Components:
      - Overview: components/index.md
      - Grid: components/grid.md
      - Button: components/button.md
      - Nav: components/nav.md
      - Modal: components/modal.md
      - Accordion: components/accordion.md
      - Alert: components/alert.md
      - Badge: components/badge.md
      - Cover: components/cover.md
      - Drop: components/drop.md
      - Dropdown: components/dropdown.md
      - Dotnav: components/dotnav.md
      - Filter: components/filter.md
      - Form: components/form.md
      - Icon: components/icon.md
      - Lightbox: components/lightbox.md
      - Offcanvas: components/offcanvas.md
      - Overlay: components/overlay.md
      - Pagination: components/pagination.md
      - Parallax: components/parallax.md
      - Placeholder: components/placeholder.md
      - Progress: components/progress.md
      - Slideshow: components/slideshow.md
      - Slider: components/slider.md
      - Sortable: components/sortable.md
      - Spinner: components/spinner.md
      - Sticky: components/sticky.md
      - Switcher: components/switcher.md
      - Table: components/table.md
      - Tab: components/tab.md
      - Tooltip: components/tooltip.md
      - Upload: components/upload.md

theme:
  name: readthedocs
